# Flutter Lints Configuration
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Elevar a ERROR para que bloquee compilacion
    use_build_context_synchronously: error
    avoid_print: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # -----------------------------------------------
    # SEGURIDAD Y ERRORES
    # -----------------------------------------------
    avoid_print: true
    use_build_context_synchronously: true
    
    # -----------------------------------------------
    # BUENAS PRACTICAS
    # -----------------------------------------------
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # -----------------------------------------------
    # PERFORMANCE
    # -----------------------------------------------
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    
    # -----------------------------------------------
    # LIMPIEZA DE CODIGO
    # -----------------------------------------------
    avoid_redundant_argument_values: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    
    # -----------------------------------------------
    # DOCUMENTACION
    # -----------------------------------------------
    public_member_api_docs: false  # Opcional: activar para librerias
